<!--
================================================================================================================ 
模板文件：/www/wwwroot/center.cncest.uk/app/code/Weline/Queue/view/templates/Backend/Queue/show.phtml START
================================================================================================================
 -->
<?php
/**@var \Weline\Framework\View\Template $this */
/**@var \Weline\Backend\Block\ThemeConfig $themeConfig */
$themeConfig = \Weline\Framework\Manager\ObjectManager::getInstance(\Weline\Backend\Block\ThemeConfig::class);
?>
<!DOCTYPE html>
<!--
 *@Author       秋枫雁飞
 *@Email        aiweline@qq.com
 *@Forum        https://bbs.aiweline.com
 *@DESC         后台共用头部
-->
<html lang='en' <?= ('rtl' === $themeConfig->getThemeModel()) ? " dir=\"rtl\"" : '' ?>>
<head>
    <!--
============================================================================================================== 
模板文件：/www/wwwroot/center.cncest.uk/vendor/weline/module-admin/view/templates/common/head.phtml START
==============================================================================================================
 -->
<?php
/**@var \Weline\Framework\View\Template $this */
/**@var \Weline\Backend\Block\ThemeConfig $themeConfig */
$themeConfig = \Weline\Framework\Manager\ObjectManager::getInstance(\Weline\Backend\Block\ThemeConfig::class);
?>
<?php
/**@var \Weline\Framework\View\Template $this */
?>
<meta charset="UTF-8">
<title><?php echo $this->getData('title'); ?></title>
<!--元数据-->
<meta content="<?php echo $this->getData('description'); ?>" name="description"/>
<meta charset='UTF-8'>
<meta name='viewport' content='width=device-width, initial-scale=1.0, shrink-to-fit=no'>
<meta content="<?php echo $this->getData('title'); ?>" name='author'/>
<meta content="<?php echo $this->getData('description'); ?>" name='description'/>
<link rel="Shortcut Icon" href="/weline/module-backend/view/statics/img/favicon.png">
<link rel="Bookmark" href="/weline/module-backend/view/statics/img/favicon.png">
<!--加载requirejs-->
<?php if (DEV) : ?>
    <!--        <script src="/weline/module-backend/view/statics/backend/lib/requirejs/2.3.6/requirejs.js"></script>-->
<?php
else:
    ?>
    <!--        <script src="/weline/module-backend/view/statics/backend/lib/requirejs/2.3.6/requirejs.min.js"></script>-->
<?php
endif;
?>
<!--加载require常用js模块-->
<!--<script src="/weline/module-backend/view/statics/base/require.configs.js"></script>-->
<?php echo framework_view_process_block([
    'class' => 'Weline\\Backend\\Block\\Header\\Base',
    'template' => 'Weline_Admin::header/base.phtml',
],$vars=[]);?>

<!--css-->
<!--loading-->
<link  href='/weline/module-admin/view/statics/libs/loading/loading.css' rel="stylesheet" type="text/css"/>
<link  href='/weline/module-admin/view/statics/backend/lib/bootstrap-5.1.3-dist/css/bootstrap.min.css' rel="stylesheet" type="text/css"/>
<link  href='/weline/module-admin/view/statics/backend/lib/font-awesome-4.7.0/css/font-awesome.min.css' rel="stylesheet" type="text/css"/>
<!-- Bootstrap Css -->
<link href="<?= $this->fetchTagSourceFile('statics', 'Weline_Admin::assets/css/bootstrap' . ($themeConfig->getThemeModel() ? '-' . $themeConfig->getThemeModel() : '') . '.min.css') ?>"
      rel="stylesheet"
      type="text/css"/>
<!-- Icons Css -->
<link  href='/weline/module-admin/view/statics/assets/css/icons.min.css' rel="stylesheet" type="text/css"/>
<!-- App Css-->
<link href="<?= $this->fetchTagSourceFile('statics', 'Weline_Admin::assets/css/app' . ($themeConfig->getThemeModel() ? '-' . $themeConfig->getThemeModel() : '') . '.min.css') ?>"
      rel="stylesheet" type="text/css"/>
<!--JS-->
<script  src='/weline/module-backend/view/statics/backend/lib/jquery/3.6.0/jquery.js'></script>
<?php if (DEV): ?>
<!--        <script src="/weline/module-backend/view/statics/backend/lib/jquery/3.6.0/jquery.map"></script>-->
<?php endif; ?>
<!--加载配置页头-->
<?php
echo $this->getHeader()->getHtml();
?>

<!--
===============================================================================================================================
模板文件：/www/wwwroot/center.cncest.uk/vendor/weline/module-admin/view/tpl/zh_Hans_CN/templates/common/com_head.phtml END
===============================================================================================================================
-->
</head>

<body <?= $themeConfig->getLayouts() ?? ''; ?>>

<!--页头工具条 开始-->
<!--
====================================================================================================================== 
模板文件：/www/wwwroot/center.cncest.uk/vendor/weline/module-admin/view/templates/common/page/loading.phtml START
======================================================================================================================
 -->
<?php
/**@var \Weline\Framework\View\Template $this */
?>
<!--Loading-->
<section id="loading">
    <div class='loader loader-1'>
        <div class='loader-outter'></div>
        <div class='loader-inner'></div>
    </div>
</section>
<script>
    function showLoading() {
        $('#loading').show()
    }

    function hideLoading() {
        $('#loading').hide()
    }

    $(function () {
        $('#loading').hide()
    })
</script>
<!--
=======================================================================================================================================
模板文件：/www/wwwroot/center.cncest.uk/vendor/weline/module-admin/view/tpl/zh_Hans_CN/templates/common/page/com_loading.phtml END
=======================================================================================================================================
-->
<!--页头工具条 结束-->

<!-- <body data-layout="horizontal" data-topbar="dark"> -->

<!-- 开始 页面 -->
<div id="layout-wrapper">
    <!-- ============================================================== -->
    <!-- Start right Content here -->
    <!-- ============================================================== -->
    <div class='page-content'>
        <div class='container-fluid'>
            <!-- start page message -->
            <div class='row'>
                <!--
============================================================================================================== 
模板文件：/www/wwwroot/center.cncest.uk/vendor/weline/module-component/view/templates/message.phtml START
==============================================================================================================
 -->
<?php
echo \Weline\Framework\Manager\ObjectManager::getInstance(\Weline\Framework\Manager\MessageManager::class);
?>
<!--
===============================================================================================================================
模板文件：/www/wwwroot/center.cncest.uk/vendor/weline/module-component/view/tpl/zh_Hans_CN/templates/com_message.phtml END
===============================================================================================================================
-->
            </div> <!-- end message -->
            <div class='row'>
                <div class='col-12'>
                    <div class='card'>
                        <div class='card-body'>
                            <h4 class='card-title'>
                                队列查看
                            </h4>
                            <p class='card-title-desc'>
                                查看队列详细信息
                            </p>
                            <!--ID-->
                            <p>
                                <b>
                                    ID
                                </b>
                                : <?=($queue['queue_id']??'') ;?><br></p>
                            <p>
                                <b>
                                    队列名称
                                </b>
                                : <?=($queue['name']??'') ;?><br></p>
                            <p>
                                <b>
                                    队列类型
                                </b>
                                : <?=($queue['t_name']??'') ;?><br></p>
                            <p>
                                <b>
                                    队列执行注意项
                                </b>
                                : <?=($queue['tip']??'') ;?><br></p>
                            <p>
                                <b>
                                    队列执行类
                                </b>
                                : <?=($queue['class']??'') ;?><br></p>
                            <p>
                                <b>
                                    队列状态
                                </b>
                                :
                                <?php if(($queue['status']??'') == 'done' ):?>
                                    <span class="badge badge-success text-success">已完成</span>
                                    <?php elseif(($queue['status']??'') == 'pending' ):?>
                                    <sapn class="badge badge-warning text-warning">
                                        等待中
                                    </sapn>
                                    <?php elseif(($queue['status']??'') == 'running' ):?>
                                    <span class="badge badge-primary text-primary">运行中</span>
                                    <?php elseif(($queue['status']??'') == 'error' ):?>
                                    <span class="badge badge-danger  text-danger">错误</span>
                                <?php endif;?>
                                <br></p>
                            <p>
                                <b>
                                    进程ID
                                </b>
                                : <?=($queue['pid']??'') ;?><br></p>
                            <p>
                                <b>
                                    开始于
                                </b>
                                : <?=($queue['start_at']??'') ;?><br></p>
                            <p>
                                <b>
                                    结束于
                                </b>
                                : <?=($queue['end_at']??'') ;?><br></p>
                            <p>
                                <b>
                                    是否结束
                                </b>
                                : <?=($queue['finished']??'') ;?><br></p>
                            <p>
                                <b>
                                    是否自动运行
                                </b>
                                : <?=($queue['auto']??'') ;?><br></p>
                            <p>
                                <b>
                                    队列数据
                                </b>
                                :
                            <div class="row">
                                <?php foreach(($queue['data']??'')  as $v):?>
                                    <div class="col-lg-4 col-md-6 col-sm-12">
                                        <?=($v['html']??'') ;?>
                                    </div>
                                <?php endforeach;?>
                            </div>
                            </p>
                            <p>
                                <b>
                                    创建时间
                                </b>
                                : <?=($queue['create_time']??'') ;?><br></p>
                            <p>
                                <b>
                                    更新时间
                                </b>
                                : <?=($queue['update_time']??'') ;?><br></p>
                            <p>
                                <b>
                                    运行结果
                                </b>
                                : <br></p>
                            <div class="card-footer">
                                <?=($queue['result']??'') ;?>
                            </div>
                        </div>
                    </div>
                </div> <!-- end col -->
            </div> <!-- end row -->
        </div> <!-- container-fluid -->
    </div>
    <!-- end main content-->
</div>
<!-- END layout-wrapper -->
<script>
    let validationEntity = $('#validationEntity')
    validationEntity.change(function () {
        let selectedOption = $(this).find(':selected').val();
        renderAttributeSet(selectedOption)
    });
    // 初始化
    let initSelected = validationEntity.find(':selected').val()
    let validationSet = $('#validationSet')
    renderAttributeSet(initSelected)

    function renderAttributeSet(entity_id) {
        $.get("<?=$this->getBackendUrl('*/backend/attribute/set/apiSearch')?>?entity_id=" + entity_id).then((res) => {
            let items = res['items']
            validationSet.empty()
            for (const itemsKey in items) {
                let item = items[itemsKey]
                let selected = '';
                if (validationSet.attr('data-selected') === item.set_id) {
                    selected = 'selected';
                }
                validationSet.append("<option value='" + item.set_id + "' " + selected + ">" + window.lang(item.name) + "</option>")
            }
        })
    }
</script>
</body>
</html>

<!--
=================================================================================================================================
模板文件：/www/wwwroot/center.cncest.uk/app/code/Weline/Queue/view/tpl/zh_Hans_CN/templates/Backend/Queue/com_show.phtml END
=================================================================================================================================
-->