<?php
/**@var \Weline\Framework\View\Template $this */
/**@var \Weline\Backend\Block\ThemeConfig $themeConfig */
$themeConfig = \Weline\Framework\Manager\ObjectManager::getInstance(\Weline\Backend\Block\ThemeConfig::class);
?>
<!DOCTYPE html>
<!--
 *@Author       秋枫雁飞
 *@Email        aiweline@qq.com
 *@Forum        https://bbs.aiweline.com
 *@DESC         后台共用头部
-->
<html lang='en' <?= ('rtl' === $themeConfig->getThemeModel()) ? " dir=\"rtl\"" : '' ?>>
<head>
    @template(Weline_Admin::common/head.phtml)
    <!-- jquery.mCustomScrollbar 插件 -->
    <link href="@static(Weline_Admin::/libs/jquery.mCustomScrollbar/jquery.mCustomScrollbar.css)" rel="stylesheet"/>
    <!-- Responsive Table css -->
    <link href='@static(Weline_Admin::assets/libs/admin-resources/rwd-table/rwd-table.min.css)' rel='stylesheet'
          type='text/css'/>
</head>

<body <?= $themeConfig->getLayouts() ?? ''; ?>>

<!--页头工具条 开始-->
@template(Weline_Admin::common/page/loading.phtml)
<!--页头工具条 结束-->

<!-- <body data-layout="horizontal" data-topbar="dark"> -->

<!-- 开始 页面 -->
<div id="layout-wrapper">


    <!--页头工具条 开始-->
    <w:block class='Weline\Admin\Block\Backend\Page\Topbar'/>
    <!--页头工具条 结束-->

    <!-- ========== Topnav Start ========== -->
    <!--页头菜单栏 开始-->
    <w:block class='Weline\Admin\Block\Backend\Page\Topnav'/>
    <!--页头菜单栏 结束-->

    <!-- ========== Left Sidebar Start ========== -->
    <!--左侧菜单栏 开始-->
    @template(Weline_Admin::common/left-sidebar.phtml)
    <!--左侧菜单栏 结束-->


    <!-- ============================================================== -->
    <!-- Start right Content here -->
    <!-- ============================================================== -->
    <div class="main-content">

        <div class='page-content'>
            <div class='container-fluid'>
                <!-- start page title -->
                <div class='row'>
                    <div class='col-12'>
                        <div class='page-title-box d-sm-flex align-items-center justify-content-between'>
                            <h4 class='mb-sm-0'>
                                <breadcrumb model="Weline\Backend\Model\Menu" order_field="order"
                                            name_field="title"></breadcrumb>
                            </h4>
                            <div class='page-title-right'>
                                <breadcrumb model='Weline\Backend\Model\Menu' order_field='order'
                                            name_field='title'></breadcrumb>
                            </div>

                        </div>
                    </div>
                </div>
                <!-- end page title -->
                <!-- start page message -->
                <div class='row'>
                    <template>Weline_Component::message.phtml</template>
                </div> <!-- end message -->
                <div class='row'>
                    <div class='col-12'>
                        <div class='card'>
                            <div class='card-body'>
                                <h4 class='card-title'>
                                    <lang>{{title}}</lang>
                                </h4>
                                <div class='table-rep-plugin'>
                                    <!-- search form -->
                                    <div class='row'>
                                        <div class='col-12'>
                                            <block class='Weline\Component\Block\Form\Search' id='queue-search'
                                                   action='*/backend/queue' method='get' keyword='q'
                                                   value=''
                                                   placeholder='请输入关键词'></block>
                                        </div>
                                    </div>
                                    <!-- end search form -->
                                    <div class='table-responsive mb-0' data-pattern='priority-columns'>
                                        <table id='tech-companies-1' class='table table-striped table-bordered'>
                                            <thead>
                                            <tr>
                                                <th data-priority='1'><?= __('队列ID') ?></th>
                                                <th data-priority='3'><?= __('进程ID') ?></th>
                                                <th data-priority='3'><?= __('类型') ?></th>
                                                <th data-priority='1'><?= __('名称') ?></th>
                                                <th data-priority='1'><?= __('开始于') ?></th>
                                                <th data-priority='1'><?= __('结束于') ?></th>
                                                <th data-priority='1'><?= __('结果') ?></th>
                                                <th data-priority='1'><?= __('内容') ?></th>
                                                <th data-priority='1'><?= __('自动消费') ?></th>
                                                <th data-priority='1'><?= __('状态') ?></th>
                                                <th data-priority='1'><?= __('是否完成') ?></th>
                                                <th data-priority='3'><?= __('创建时间') ?></th>
                                                <th data-priority='3'><?= __('更新时间') ?></th>
                                                <th data-priority='3'><?= __('操作') ?></th>
                                            </tr>
                                            </thead>
                                            <tbody>
                                            <foreach name="queues" item="queue" key="key">
                                                <tr>
                                                    <td>{{queue.queue_id}}</td>
                                                    <td>{{queue.pid}}</td>
                                                    <td>{{queue.t_name}}</td>
                                                    <td class='co-name'>{{queue.name}}</td>
                                                    <td class='co-name'>{{queue.start_at}}</td>
                                                    <td class='co-name'>{{queue.end_at}}</td>
                                                    <td class='co-name'>{{queue.result}}</td>
                                                    <td class='co-name' style="max-width:120px;overflow: scroll">{{queue.content}}</td>
                                                    <td class='co-name'>{{queue.auto}}</td>
                                                    <td class='co-name'>{{queue.status}}</td>
                                                    <td class='co-name'>{{queue.finished}}</td>
                                                    <td class='co-name'>{{queue.create_time}}</td>
                                                    <td class='co-name'>{{queue.update_time}}</td>
                                                    <td class='co-name'>
                                                        <div class="d-flex gap-2">
                                                            <a class='btn btn-info' href="@backend-url('*/backend/queue/edit')?code={{queue
                                                                .queue_id}}">
                                                                <lang>修改</lang>
                                                            </a>
                                                            <a class='btn btn-danger' href="@backend-url('*/backend/queue/delete')?code={{queue
                                                                .queue_id}}">
                                                                <lang>删除</lang>
                                                            </a>
                                                        </div>
                                                    </td>
                                                </tr>
                                            </foreach>
                                            </tbody>
                                        </table>
                                        {{pagination}}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div> <!-- end col -->
                </div> <!-- end row -->
            </div> <!-- container-fluid -->
        </div>
        <!-- End Page-content -->

        <footer class="footer">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-sm-6">
                        <script>document.write(new Date().getFullYear())</script>
                        © Weline.
                    </div>
                    <div class="col-sm-6">
                        <div class="text-sm-end d-none d-sm-block">
                            Crafted with <i class="mdi mdi-heart text-danger"></i> By <a
                                href="https://www.aiweline.com/">秋枫雁飞(aiweline)</a>
                        </div>
                    </div>
                </div>
            </div>
        </footer>

    </div>
    <!-- end main content-->

</div>
<!-- END layout-wrapper -->
<!--右边栏-->
@template(Weline_Admin::common/right-sidebar.phtml)

<!-- Table Editable plugin -->
<script src="@static(Weline_Admin::assets/libs/table-edits/build/table-edits.min.js)"></script>
<script src="@static(Weline_Admin::assets/js/pages/menus/table-editable.init.js)"></script>
<script src='@static(Weline_Admin::/libs/jquery.mCustomScrollbar/jquery.mCustomScrollbar.concat.min.js)'></script>
<!-- Responsive Table js -->
<script src='@static(Weline_Admin::assets/libs/admin-resources/rwd-table/rwd-table.min.js)'></script>

<!-- Init js -->
<script src='@static(Weline_Admin::assets/js/pages/table-responsive.init.js)'></script>
@template(Weline_Admin::common/footer.phtml)
</body>
</html>
